### ISSUE TITLE
Regexp routes are broken

### ISSUE THREAD

**Issue by ricardo-nog** [alexmingoia/koa-router#191]
This error is caused by #183 changes.

+1 on #188 which fixes it.

```
node_modules/koa-router/lib/router.js:513
      var routeNestingLevel = route.path.split('/').length;
                                         ^

TypeError: route.path.split is not a function

**Comment by ricardo-nog** [comment]
Duplicated of #181.
